# deez iz my aliases innit
alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ls -A'
alias l='ls'
alias less='less -S'
alias shuffle='vlc -Z $HOME/music/ 2> /dev/null &'
alias tufts='ssh -X ashapi02@homework.cs.tufts.edu'
alias bucknell='ssh -X as059@linuxremote1.eg.bucknell.edu'
alias spanish='setxkbmap -layout us -variant altgr-intl'
alias :q='exit'
alias bigger='printf '\''\e]710;%s\007'\'' 7x13bold'
alias normal='printf '\''\e]710;%s\007'\'' 6x13'
alias ncmpcpp='ncmpcpp 2> /dev/null'
alias mopidy='ncmpcpp -h m140 -p 6602 -s browser 2> /dev/null'
alias stereo='ncmpcpp -h m140 -p 6600 2> /dev/null'
alias rshuffle='env MPD_HOST=m140 ashuffle'
alias sightline='ssh -X as059@172.20.20.20'
