# deez iz my aliases innit
alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ls -A'
alias l='ls'
alias less='less -S'
alias tufts='ssh ashapi02@homework.cs.tufts.edu'
alias bucknell='ssh as059@linuxremote1.eg.bucknell.edu'
alias spanish='setxkbmap -layout us -variant altgr-intl'
alias :q='exit'
alias bigger='printf '\''\e]710;%s\007'\'' xft:terminus:size=12'
alias normal='printf '\''\e]710;%s\007'\'' 6x13'
alias ncmpcpp='ncmpcpp 2> /dev/null'
alias rshuffle='env MPD_HOST=m140 ashuffle'
alias lua='lua5.3'
alias aom='wine /home/adon/.wine/drive_c/Program\ Files/Microsoft\ Games/Age\ of\ Mythology/aom.exe +noIntroCinematics'
alias fs2002='wine /home/adon/.wine/drive_c/Program\ Files/Microsoft\ Games/FS2002/fs2002.exe'
alias start-vms='for i in {arch,fedora}; do sudo virsh start $i; done'
